### ISSUE TITLE
Errors on API or something else?

### ISSUE THREAD

**Issue by djjassu** [arska/controlmyspa-porssari#28]
After cloning and running, there is different errors :

Job "control (trigger: date[2024-03-25 12:42:56 UTC], next run at: 2024-03-25 12:42:56 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/app.py", line 187, in control
    if int(os.getenv("TEMP_OVERRIDE", "0")):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '0 # override the temperature logic, for example, during vacation'
Job "control (trigger: cron[minute='*/15'], next run at: 2024-03-25 13:00:00 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/app.py", line 187, in control
    if int(os.getenv("TEMP_OVERRIDE", "0")):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '0 # override the temperature logic, for example, during vacation'
[2024-03-25 12:47:22,335] INFO in before_sleep: Retrying <unknown> in 0.12529375524194952 seconds as it raised HTTPError: 401 Client Error: Unauthorized for url: https://iot.controlmyspa.com/auth/oxauth/restv1/tokenEntra.
[2024-03-25 12:47:25,630] INFO in before_sleep: Retrying <unknown> in 0.25681424936481756 seconds as it raised HTTPError: 401 Client Error: Unauthorized for url: https://iot.controlmyspa.com/auth/oxauth/restv1/tokenEntra.
[2024-03-25 12:47:28,998] INFO in before_sleep: Retrying <unknown> in 3.1578318865520245 seconds as it raised HTTPError: 401 Client Error: Unauthorized for url: https://iot.controlmyspa.com/auth/oxauth/restv1/tokenEntra.
[2024-03-25 12:47:35,610] INFO in before_sleep: Retrying <unknown> in 6.558111264061721 seconds as it raised HTTPError: 401 Client Error: Unauthorized for url: https://iot.controlmyspa.com/auth/oxauth/restv1/tokenEntra.

****

Configuration error, or something on Balboas side perhaps?

**Comment by arska** [comment]
Hello @djjassu
Sorry, I didn't notice your issue until now; mentioning me helps me get notifications :)
The error seems to come from the comment after the "TEMP_OVERRIDE" value in your .env file. Can you run the example successfully by removing the comment after "#", so just "TEMP_OVERRIDE=0" on a line?
Cheers, Aarno
